---
- name: Create install directory
  file:
    path: "{{ install_directory }}/{{ role_name }}"
    state: directory
    owner: debian
    group: debian
  become: true

- name: Copy traefik.yml file to destination
  template:
    src: traefik.yml
    dest: "{{ install_directory }}/{{ role_name }}/traefik.yml"
    owner: debian
    group: debian
  become: true

- name: Copy docker-compose file to destination
  template:
    src: docker-compose.yml
    dest: "{{ install_directory }}/{{ role_name }}/docker-compose.yml"
    owner: debian
    group: debian
    validate: docker compose -f %s config
  become: true

- name: Run docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ install_directory }}/{{ role_name }}"
  register: output
