---
- name: Create install directory
  file:
    path: "{{ install_directory }}/{{ role_name }}"
    state: directory
    owner: ubuntu
    group: ubuntu
  become: true

- name: Create config directory
  file:
    path: "{{ data_dir }}/{{ role_name }}"
    state: directory
    owner: ubuntu
    group: ubuntu
  become: true

- name: Create certificate directory
  file:
    path: "{{ data_dir }}/{{ role_name }}/letsencrypt"
    state: directory
    owner: "ubuntu"
  become: true

- name: Copy traefik.yml file to destination
  template:
    src: traefik.yml
    dest: "{{ data_dir }}/{{ role_name }}/{{ role_name }}.yml"
    owner: ubuntu
    group: ubuntu
  become: true

- name: Copy docker-compose file to destination
  template:
    src: docker-compose.yml
    dest: "{{ install_directory }}/{{ role_name }}/docker-compose.yml"
    owner: ubuntu
    group: ubuntu
    validate: docker compose -f %s config
  become: true

- name: Run docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ install_directory }}/{{ role_name }}"
  register: output
