globalArguments:
  - "--global.checknewversion"
  - "--global.sendanonymoususage"

additionalArguments:
  - "--serverstransport.insecureskipverify=true"

ports:
  web:
    redirectTo:
      port: websecure
  websecure:
    tls:
      enabled: true

tlsStore:
  default:
    defaultCertificate:
      secretName: rizexor-me-tls
