apiVersion: apps/v1
kind: Deployment
metadata:
  name: arr-stack
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arr-stack
  template:
    metadata:
      labels:
        app: arr-stack
    spec:
      containers:
        - name: jellyfin
          image: ghcr.io/hotio/jellyfin:release-10.10.3
          ports:
            - containerPort: 8096
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Kolkata"
          volumeMounts:
            - name: jellyfin-config
              mountPath: /config
        - name: radarr
          image: ghcr.io/hotio/radarr:release-5.17.2.9580
          ports:
            - containerPort: 7878
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Kolkata"
          # volumeMounts:
          #   - name: radarr-config
          #     mountPath: /config
          #   - name: arr-stack-data
          #     mountPath: /data/media
      volumes:
        - name: jellyfin-config
          nfs:
            server: 192.168.2.180
            path: "/srv/nfs4/config/jellyfin"
