apiVersion: apps/v1
kind: Deployment
metadata:
  name: arr-stack
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arr-stack
  template:
    metadata:
      labels:
        app: arr-stack
    spec:
      containers:
        - name: jellyfin
          image: ghcr.io/hotio/jellyfin:release-10.10.3
          ports:
            - containerPort: 8096
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Kolkata"
          volumeMounts:
            - name: jellyfin-config
              mountPath: /config
            - name: jellyfin-data
              mountPath: /data/media
        - name: radarr
          image: ghcr.io/hotio/radarr:release-5.17.2.9580
          ports:
            - containerPort: 7878
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Kolkata"
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: radarr-data
              mountPath: /data/media
      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: jellyfin-data
          persistentVolumeClaim:
            claimName: jellyfin-data
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: radarr-data
          persistentVolumeClaim:
            claimName: jellyfin-data
