apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: arr-stack
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arr-stack
  template:
    metadata:
      labels:
        app: arr-stack
    spec:
      containers:
        - name: jellyfin
          image: ghcr.io/hotio/jellyfin@sha256:cd32bc1491d128a4b1bf4a5de66cfa5f2c687c3c4ea6ee2f0d9c2f95114cd5d6
          ports:
            - containerPort: 8096
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Kolkata"
            - name: JELLYFIN_PublishedServerUrl
              value: "https://jellyfin.home.rizexor.com"
          volumeMounts:
            - name: jellyfin-config
              mountPath: /config
            - name: data
              mountPath: /data
        - name: radarr
          image: ghcr.io/hotio/radarr@sha256:7f583b35dca64c1bffd27a39d61d4c3143633a29070260f76f1e5939006780d8
          ports:
            - containerPort: 7878
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Kolkata"
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: data
              mountPath: /data
        - name: sonarr
          image: ghcr.io/hotio/sonarr@sha256:ce095ff23043fe1397ac663d7d0885fbabdce9809257931ae9646c04d89567e8
          ports:
            - containerPort: 8989
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Kolkata"
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: data
              mountPath: /data
        - name: sabnzbd
          image: ghcr.io/hotio/sabnzbd@sha256:aff501a8144b64f8bd318768e37987d7d6c02c41b95917519343eb960c41ae0a
          ports:
            - containerPort: 8080
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Kolkata"
            - name: WEBUI_PORTS
              value: "8080/tcp,8080/udp"
          volumeMounts:
            - name: sabnzbd-config
              mountPath: /config
            - name: data
              mountPath: /data
        - name: prowlarr
          image: ghcr.io/hotio/prowlarr@sha256:0fc62cbb850542dc235581986e9f64b774f08d3dfbe29f96a5c1177819f1b8a3
          ports:
            - containerPort: 9696
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Kolkata"
          volumeMounts:
            - name: prowlarr-config
              mountPath: /config
        - name: recyclarr
          image: ghcr.io/recyclarr/recyclarr:7.4
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: TZ
              value: "Asia/Kolkata"
          volumeMounts:
            - name: recyclarr-config
              mountPath: /config
      volumes:
        - name: data
          nfs:
            server: 192.168.2.180
            path: "/srv/nfs4/data"
        - name: jellyfin-config
          nfs:
            server: 192.168.2.180
            path: "/srv/nfs4/config/jellyfin"
        - name: radarr-config
          nfs:
            server: 192.168.2.180
            path: "/srv/nfs4/config/radarr"
        - name: sonarr-config
          nfs:
            server: 192.168.2.180
            path: "/srv/nfs4/config/sonarr"
        - name: prowlarr-config
          nfs:
            server: 192.168.2.180
            path: "/srv/nfs4/config/prowlarr"
        - name: recyclarr-config
          nfs:
            server: 192.168.2.180
            path: "/srv/nfs4/config/recyclarr"
        - name: sabnzbd-config
          nfs:
            server: 192.168.2.180
            path: "/srv/nfs4/config/sabnzbd"
