---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arr-stack
  namespace: homelab
spec:
  ingressClassName: nginx
  rules:
    - host: arr-stack.rizexor.local
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: arr-stack
              port:
                number: 80
