---
apiVersion: v1
kind: Service
metadata:
  name: arr-stack
  namespace: homelab
spec:
  type: ClusterIP
  ports:
    - name: jellyfin
      port: 8096
      targetPort: 8096
    - name: radarr
      port: 7878
      targetPort: 7878
  selector:
    app: arr-stack

