---
version: "3.9"
networks:
  traefik:
    external: false
    name: traefik

services:
  traefik:
    container_name: traefik
    image: traefik:v2.10
    command: --providers.docker
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

