---
version: "3.9"
networks:
  traefik:
    external: false
    name: traefik

services:
  traefik:
    container_name: traefik
    image: traefik:v2.10
    command: --providers.docker
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_API_EMAIL: {{ CF_API_EMAIL }}
      - CF_API_KEY: {{ CF_API_KEY }}
    volumes:
      - "{{ data_dir }}/letsencrypt:/letsencrypt"
      - "{{ data_dir }}/traefik.yml:/traefik.yml:ro"
      - /var/run/docker.sock:/var/run/docker.sock

