---
# api:
#   dashboard: false
#   debug: false
#   insecure: false

providers:
  docker:
    exposedByDefault: false

log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: cloudflare-production
        domains:
          - main: 's.{{ domain }}'
            sans:
              - '*.s.{{ domain }}'

certificatesResolvers:
  cloudflare-production:
    acme:
      email: "{{ email }}"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "192.168.2.1:53"
  lets-encrypt-staging:
    acme:
      email: "{{ email }}"
      storage: "/letsencrypt/acme.json"
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "192.168.2.1:53"
