---
version: '3'
services:
  reverse-proxy:
    image: traefik:v2.10
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/acme.json:/acme.json
  cmrl-web3-backend:
    image: rizexor/cmrl-web3-backend:main
    container_name: cmrl-web3-backend
    labels:
      - traefik.http.routers.my-container.rule=Host(`cmrl-web3-backend.pb.rizexor.me`)
