apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  source:
    chart: authentik
    repoURL: https://charts.goauthentik.io/
    targetRevision: 2024.12.3
    helm:
      valuesObject:
        authentik:
          secret_key: file:///authentik-secret-key/secret-key
          error_reporting:
              enabled: true
          postgresql:
            name: app
            host: authentik-rw
            user: file:///postgres-creds/username
            password: file:///postgres-creds/password
          email:
            host: file:///smtp-creds/host
            port: 587
            username: file:///smtp-creds/username
            password: file:///smtp-creds/password
            use_tls: true
            timeout: 30
            from: file:///smtp-creds/from

        worker:
          volumes:
            - name: postgres-creds
              secret:
                secretName: authentik-app
            - name: smtp-creds
              secret:
                secretName: smtp-creds
            - name: authentik-secret-key
              secret:
                secretName: authentik-secret-key
          volumeMounts:
            - name: postgres-creds
              mountPath: /postgres-creds
              readOnly: true
            - name: smtp-creds
              mountPath: /smtp-creds
              readOnly: true
            - name: authentik-secret-key
              mountPath: /authentik-secret-key
              readOnly: true

        server:
          volumes:
            - name: postgres-creds
              secret:
                secretName: authentik-app
            - name: smtp-creds
              secret:
                secretName: smtp-creds
            - name: authentik-secret-key
              secret:
                secretName: authentik-secret-key
          volumeMounts:
            - name: postgres-creds
              mountPath: /postgres-creds
              readOnly: true
            - name: smtp-creds
              mountPath: /smtp-creds
              readOnly: true
            - name: authentik-secret-key
              mountPath: /authentik-secret-key
              readOnly: true
          ingress:
              ingressClassName: nginx
              enabled: true
              hosts:
                  - authentik.home.rizexor.com

        redis:
            enabled: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: authentik
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik
  namespace: authentik
spec:
  instances: 1
  storage:
    size: 3Gi
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-creds
  namespace: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: smtp-creds

  data:
    - secretKey: host
      remoteRef:
        key: SMTP_HOST
    - secretKey: username
      remoteRef:
        key: SMTP_USERNAME
    - secretKey: password
      remoteRef:
        key: SMTP_PASSWORD
    - secretKey: from
      remoteRef:
        key: SMTP_FROM
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: authentik-secret-key

  data:
    - secretKey: secret-key
      remoteRef:
        key: AUTHENTIK_SECRET_KEY
