apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  source:
    chart: authentik
    repoURL: https://charts.goauthentik.io/
    targetRevision: 2024.12.2
    helm:
      valuesObject:
        authentik:
            secret_key: "mb6xDFv3Pg7UKd2/C0W0EVe4TS/9dbtNh+V+nY/uBOoYJsryD96fvQM1bTIGilZgnKCG+Y8xGdxzcKQv"
            error_reporting:
                enabled: true
            postgresql:
              host: authentik-rw
              user: file:///postgres-creds/username
              password: file:///postgres-creds/password

        server:
          volumes:
            - name: postgres-creds
              secret:
                secretName: authentik-postgres-credentials
          volumeMounts:
            - name: postgres-creds
              mountPath: /postgres-creds
              readOnly: true
          ingress:
              ingressClassName: nginx
              enabled: true
              hosts:
                  - authentik.home.rizexor.com

        redis:
            enabled: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: authentik
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik
  namespace: authentik
spec:
  instances: 1
  storage:
    size: 3Gi
