apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.16.2
    helm:
      parameters:
      - name: "crds.enabled"
        value: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: infisical-managed-secrets
  namespace: homelab
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: cloudflare-token-key-secret

  data:
    - secretKey: api-token
      remoteRef:
        key: CLOUDFLARE_API_TOKEN_SECRET
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare-issuer
  namespace: homelab
spec:
  acme:
    email: certs@rize.anonaddy.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab
  namespace: homelab
spec:
  secretName: homelab
  dnsNames:
    - 'home.rizexor.com'
    - '*.home.rizexor.com'
  issuerRef:
    name: cloudflare-issuer
    kind: Issuer
