apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.12.1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: default
            name: infisical-universal-auth-credentials
          clientSecret:
            key: clientSecret
            namespace: default
            name: infisical-universal-auth-credentials
      secretsScope:
        projectSlug: homelab-hp-rr
        environmentSlug: prod
        # optional
        secretsPath: / # Root is "/"
        # optional
        recursive: true # Default is false
      hostAPI: https://app.infisical.com
