apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 75.7.0
    helm:
      valuesObject:
        grafana:
          ingress:
            enabled: true
            hosts:
            - grafana.home.rizexor.com
            tls:
            - secretName: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: homelab
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
