---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argocd
spec:
  project: default
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    targetRevision: 4.0.18
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nfs-provisioner
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
