apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k3s-rizexor-me
  namespace: default
spec:
  secretName: rizexor-me-staging-tls
  dnsNames:
    - "k3s.rizexor.me"
    - "*.k3s.rizexor.me"
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-staging
    kind: Issuer