apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: decodestudios.help@gmail.com

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod

    # ACME DNS-01 provider configurations
    solvers:
      - dns01:
          cloudflare:
            email: decodestudios.help@gmail.com
            apiKeySecretRef:
              name: cloudflare-api-key-secret
              key: api-token
