apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: default
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: decodestudios.help@gmail.com

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging

    # ACME DNS-01 provider configurations
    solvers:
    - selector:
        dnsZones:
        - rizexor.me
      dns01:
        cloudflare:
          email: decodestudios.help@gmail.com
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-token