apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: audiobookshelf
  namespace: argocd
spec:
  project: default
  source:
    path: audiobookshelf
    repoURL: https://github.com/navaneeth-dev/homelab
    targetRevision: HEAD
    path: manifests/audiobookshelf
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
