services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.s.{{ domain }}`)
      - traefik.http.routers.radarr.entrypoints=websecure
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sonarr:/config
      - /data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`sonarr.s.{{ domain }}`)
      - traefik.http.routers.sonarr.entrypoints=websecure
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/bazarr:/config
      - /data/media:/data/media
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr.rule=Host(`bazarr.s.{{ domain }}`)
      - traefik.http.routers.bazarr.entrypoints=websecure
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sabnzbd:/config
      - /data/usenet:/data/usenet:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.s.{{ domain }}`)
      - traefik.http.routers.sabnzbd.entrypoints=websecure
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    restart: unless-stopped
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/prowlarr:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.s.{{ domain }}`)
      - traefik.http.routers.prowlarr.entrypoints=websecure
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - /docker/appdata/recyclarr:/config
    environment:
      - TZ=Asia/Kolkata
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin:latest
    restart: unless-stopped
    ports:
      - 8096:8096
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/jellyfin:/config
      - /data/media:/data/media
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.s.{{ domain }}`)
      - traefik.http.routers.jellyfin.entrypoints=websecure
  jellyseerr:
    container_name: jellyseerr
    image: ghcr.io/hotio/jellyseerr
    restart: unless-stopped
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/jellyseerr:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.s.{{ domain }}`)
      - traefik.http.routers.jellyseerr.entrypoints=websecure
  librespeed:
    container_name: librespeed
    image: ghcr.io/librespeed/speedtest:latest
    restart: unless-stopped
    environment:
      MODE: standalone
    ports:
      - 60000:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.librespeed.rule=Host(`librespeed.s.{{ domain }}`)
      - traefik.http.routers.librespeed.entrypoints=websecure
  backup:
    container_name: backup
    image: mazzolino/restic
    hostname: docker
    restart: unless-stopped
    environment:
      RUN_ON_STARTUP: "false"
      BACKUP_CRON: "0 0 23 * * *"
      RESTIC_REPOSITORY: {{ RESTIC_REPOSITORY }}
      RESTIC_PASSWORD: {{ RESTIC_PASSWORD }}
      RESTIC_BACKUP_SOURCES: /mnt/volumes
      RESTIC_BACKUP_ARGS: >-
        --tag docker-volumes
        --exclude='*.tmp'
        --verbose
      RESTIC_FORGET_ARGS: >-
        --keep-last 10
        --keep-daily 7
        --keep-weekly 5
        --keep-monthly 12
      AWS_ACCESS_KEY_ID: {{ AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: {{ AWS_SECRET_ACCESS_KEY }}
      TZ: {{ timezone }}
    volumes:
      - /mnt/restore:/mnt/restore
      - /docker/appdata:/mnt/volumes:ro
  prune:
    image: mazzolino/restic
    hostname: docker
    restart: unless-stopped
    environment:
      RUN_ON_STARTUP: "false"
      PRUNE_CRON: "0 0 4 * * *"
      RESTIC_REPOSITORY: {{ RESTIC_REPOSITORY }}
      RESTIC_PASSWORD: {{ RESTIC_PASSWORD }}
      AWS_ACCESS_KEY_ID: {{ AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: {{ AWS_SECRET_ACCESS_KEY }}
      TZ: {{ timezone }}
  check:
    image: mazzolino/restic
    hostname: docker
    restart: unless-stopped
    environment:
      RUN_ON_STARTUP: "false"
      CHECK_CRON: "0 15 5 * * *"
      RESTIC_CHECK_ARGS: >-
        --read-data-subset=10%
      RESTIC_REPOSITORY: {{ RESTIC_REPOSITORY }}
      RESTIC_PASSWORD: {{ RESTIC_PASSWORD }}
      AWS_ACCESS_KEY_ID: {{ AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: {{ AWS_SECRET_ACCESS_KEY }}
      TZ: {{ timezone }}

networks:
  default:
    name: traefik
    external: true
